version: "3.8"
services:
  nextjs-static:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Optional volume for development to see changes without rebuilding
    # volumes:
    #   - ./out:/usr/share/nginx/html
